spring.application.name=jdt17.spring.rest.api

spring.datasource.url=jdbc:postgresql://localhost:5432/jdt17_api
spring.datasource.username=postgres
spring.datasource.password=verry
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

